### ISSUE TITLE
csv file aanpassen

### ISSUE THREAD

**Issue by eugenetake** [eugenetake/php-opdracht#1]
er zitten fouten in de csv file waardoor hij niet goed gelezen kan worden

**Comment by Perensoep109** [comment]
Eywa niggers die fout ga ik fixen a niffo

**Comment by Perensoep109** [comment]
Bijna gefixed makkers

**Comment by Perensoep109** [comment]
reddit.com/r/cirkeltrek

**Comment by serenatake** [comment]
dude we moeten serieus aan deze opdracht werken

**Comment by Perensoep109** [comment]
![image](https://user-images.githubusercontent.com/19958930/55712032-3fdc4700-59ee-11e9-825e-26a3bd4c3e09.png)

**Comment by serenatake** [comment]
and its closed
